"""
Destination catalogue for the AI Travel Itinerary Generator.

This file holds static travel data only. Recommendation rules live in
recommendation_engine.py and the Streamlit UI lives in app.py.
"""

ALL_TYPES = ["Solo", "Couple", "Family", "Friends"]
ADULTS = ["Solo", "Couple", "Friends"]
FAMILY_FRIENDLY = ["Solo", "Couple", "Family", "Friends"]


def _spot(name, category, cost, hours, time_of_day, types=None, note=""):
    """Build one attraction record with a consistent shape."""
    return {
        "name": name,
        "category": category,
        "estimated_cost": cost,
        "duration_hours": hours,
        "best_time": time_of_day,
        "suitable_types": list(types or FAMILY_FRIENDLY),
        "note": note,
    }


# Alternate spellings so typed input still matches the catalogue.
DESTINATION_ALIASES = {
    "bangalore": "Bengaluru",
    "bengaluru": "Bengaluru",
    "mysore": "Mysuru",
    "mysuru": "Mysuru",
    "goa": "Goa",
    "mumbai": "Mumbai",
    "bombay": "Mumbai",
    "delhi": "Delhi",
    "new delhi": "Delhi",
    "newdelhi": "Delhi",
    "jaipur": "Jaipur",
    "hyderabad": "Hyderabad",
    "chennai": "Chennai",
    "madras": "Chennai",
    "kochi": "Kochi",
    "cochin": "Kochi",
    "ooty": "Ooty",
    "udhagamandalam": "Ooty",
    "manali": "Manali",
    "munnar": "Munnar",
}


DESTINATIONS = {
    "Bengaluru": {
        "state": "Karnataka",
        "tagline": "India's Garden City of parks, palaces and cafes",
        "weather_note": "Mild weather most of the year; evenings can be cool.",
        "is_hill_station": False,
        "is_beach": False,
        "attractions": [
            _spot("Lalbagh Botanical Garden", "Nature", 20, 2.0, "Morning", note="Glass House and heritage trees"),
            _spot("Cubbon Park stroll", "Relaxation", 0, 1.5, "Morning"),
            _spot("Bangalore Palace", "History", 230, 2.0, "Morning"),
            _spot("Tipu Sultan's Summer Palace", "History", 20, 1.5, "Afternoon"),
            _spot("ISKCON Temple Bengaluru", "Culture", 0, 2.0, "Morning"),
            _spot("Visvesvaraya Industrial & Technological Museum", "Culture", 50, 2.0, "Afternoon", FAMILY_FRIENDLY),
            _spot("Bannerghatta Biological Park", "Nature", 300, 3.5, "Morning", FAMILY_FRIENDLY),
            _spot("Nandi Hills sunrise trip", "Adventure", 700, 5.0, "Morning", ADULTS),
            _spot("Commercial Street shopping", "Shopping", 500, 2.0, "Afternoon"),
            _spot("UB City and Lavelle Road", "Shopping", 800, 2.0, "Afternoon", ADULTS),
            _spot("Vidyarthi Bhavan breakfast", "Food", 180, 1.0, "Morning"),
            _spot("VV Puram food street", "Food", 350, 1.5, "Evening"),
            _spot("Church Street cafe crawl", "Food", 450, 2.0, "Afternoon", ADULTS),
            _spot("MG Road & Brigade Road evening", "Nightlife", 250, 2.0, "Evening", ADULTS),
            _spot("Ulsoor Lake walk", "Relaxation", 0, 1.5, "Evening"),
            _spot("Wonderla Amusement Park", "Adventure", 1400, 5.0, "Morning", FAMILY_FRIENDLY),
            _spot("National Gallery of Modern Art", "Culture", 20, 2.0, "Afternoon"),
            _spot("Koramangala nightlife", "Nightlife", 900, 2.5, "Evening", ["Friends", "Couple"]),
            _spot("Bull Temple & Dodda Ganesha", "Culture", 0, 1.5, "Morning"),
            _spot("Halasuru Someshwara Temple", "History", 0, 1.0, "Evening"),
        ],
    },
    "Mysuru": {
        "state": "Karnataka",
        "tagline": "Royal heritage, silk and sandalwood",
        "weather_note": "Warm days; comfortable for walking palace precincts.",
        "is_hill_station": False,
        "is_beach": False,
        "attractions": [
            _spot("Mysore Palace (Amba Vilas)", "History", 70, 2.5, "Morning"),
            _spot("Chamundi Hill & Temple", "Culture", 50, 2.5, "Morning"),
            _spot("St. Philomena's Cathedral", "Culture", 0, 1.0, "Afternoon"),
            _spot("Brindavan Gardens", "Nature", 40, 2.0, "Evening"),
            _spot("Mysore Zoo (Sri Chamarajendra)", "Nature", 80, 2.5, "Morning", FAMILY_FRIENDLY),
            _spot("Jaganmohan Palace Art Gallery", "Culture", 30, 1.5, "Afternoon"),
            _spot("Devaraja Market spices & flowers", "Shopping", 300, 1.5, "Morning"),
            _spot("Silk and sandalwood shopping", "Shopping", 800, 2.0, "Afternoon"),
            _spot("Mysore pak tasting trail", "Food", 200, 1.0, "Afternoon"),
            _spot("K.R. Circle evening walk", "Relaxation", 0, 1.0, "Evening"),
            _spot("Karanji Lake bird watching", "Nature", 20, 1.5, "Morning"),
            _spot("Railway Museum Mysuru", "History", 20, 1.5, "Afternoon", FAMILY_FRIENDLY),
            _spot("Illuminated palace night view", "Culture", 200, 1.5, "Evening"),
            _spot("Local thali lunch", "Food", 250, 1.0, "Afternoon"),
            _spot("Chamundi Hill trekking path", "Adventure", 0, 2.5, "Morning", ADULTS),
            _spot("KRS Dam viewpoint", "Nature", 30, 2.0, "Evening"),
            _spot("Folklore Museum", "Culture", 30, 1.5, "Afternoon"),
            _spot("Evening filter coffee on Sayyaji Rao Road", "Food", 80, 0.75, "Evening"),
        ],
    },
    "Goa": {
        "state": "Goa",
        "tagline": "Beaches, spice, Portuguese streets and sunsets",
        "weather_note": "Hot and humid; carry sunscreen and light cottons.",
        "is_hill_station": False,
        "is_beach": True,
        "attractions": [
            _spot("Baga Beach morning swim", "Relaxation", 0, 2.0, "Morning"),
            _spot("Calangute Beach walk", "Relaxation", 0, 1.5, "Afternoon"),
            _spot("Anjuna flea market", "Shopping", 600, 2.5, "Afternoon"),
            _spot("Fort Aguada", "History", 0, 2.0, "Morning"),
            _spot("Basilica of Bom Jesus", "Culture", 0, 1.5, "Morning"),
            _spot("Old Goa churches circuit", "History", 0, 2.5, "Morning"),
            _spot("Dudhsagar Falls day trip", "Adventure", 1800, 6.0, "Morning", ADULTS),
            _spot("Spice plantation tour", "Nature", 500, 2.5, "Afternoon", FAMILY_FRIENDLY),
            _spot("Fontainhas Latin Quarter walk", "Culture", 0, 2.0, "Evening"),
            _spot("Goan seafood lunch", "Food", 700, 1.5, "Afternoon"),
            _spot("Bebinca & feni tasting", "Food", 400, 1.0, "Evening", ADULTS),
            _spot("Sunset at Palolem / Candolim", "Relaxation", 0, 1.5, "Evening"),
            _spot("Water sports at Baga", "Adventure", 1200, 2.0, "Morning", ADULTS),
            _spot("Night bazaar at Arpora", "Shopping", 500, 2.0, "Evening"),
            _spot("Tito's / Baga nightlife", "Nightlife", 1200, 3.0, "Evening", ["Friends", "Couple"]),
            _spot("Dolphin spotting boat ride", "Adventure", 800, 2.0, "Morning", FAMILY_FRIENDLY),
            _spot("Panaji riverside promenade", "Relaxation", 0, 1.5, "Evening"),
            _spot("Reis Magos Fort", "History", 50, 1.5, "Afternoon"),
            _spot("Mapusa market morning", "Shopping", 350, 1.5, "Morning"),
        ],
    },
    "Mumbai": {
        "state": "Maharashtra",
        "tagline": "Maximum city of sea, cinema and street food",
        "weather_note": "Humid coastal weather; plan indoor breaks in peak afternoon heat.",
        "is_hill_station": False,
        "is_beach": True,
        "attractions": [
            _spot("Gateway of India", "History", 0, 1.0, "Morning"),
            _spot("Elephanta Caves ferry", "History", 250, 4.0, "Morning"),
            _spot("Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", "Culture", 120, 2.0, "Afternoon"),
            _spot("Marine Drive sunset", "Relaxation", 0, 1.5, "Evening"),
            _spot("Chowpatty beach & bhel", "Food", 150, 1.5, "Evening", FAMILY_FRIENDLY),
            _spot("Colaba Causeway shopping", "Shopping", 600, 2.0, "Afternoon"),
            _spot("Crawford Market", "Shopping", 400, 1.5, "Morning"),
            _spot("Siddhivinayak Temple", "Culture", 0, 1.5, "Morning"),
            _spot("Haji Ali Dargah", "Culture", 0, 1.5, "Afternoon"),
            _spot("Bandra-Worli Sea Link view", "Relaxation", 0, 1.0, "Evening"),
            _spot("Street food at Mohammed Ali Road / Khau Galli", "Food", 350, 1.5, "Evening", ADULTS),
            _spot("Juhu Beach evening", "Relaxation", 0, 1.5, "Evening", FAMILY_FRIENDLY),
            _spot("Sanjay Gandhi National Park & Kanheri", "Nature", 100, 3.5, "Morning"),
            _spot("Bollywood studio tour", "Culture", 1500, 3.0, "Afternoon", FAMILY_FRIENDLY),
            _spot("Bandra cafe hopping", "Food", 700, 2.0, "Afternoon", ADULTS),
            _spot("Lower Parel nightlife", "Nightlife", 1500, 3.0, "Evening", ["Friends", "Couple"]),
            _spot("Hanging Gardens & Malabar Hill", "Nature", 0, 1.5, "Morning"),
            _spot("Dhobi Ghat viewpoint", "Culture", 0, 0.75, "Morning"),
            _spot("Kala Ghoda art walk", "Culture", 0, 2.0, "Afternoon"),
        ],
    },
    "Delhi": {
        "state": "Delhi",
        "tagline": "Capitals old and new: forts, food and bazaars",
        "weather_note": "Extreme seasons — summers are hot, winters are foggy and cold.",
        "is_hill_station": False,
        "is_beach": False,
        "attractions": [
            _spot("Red Fort", "History", 35, 2.0, "Morning"),
            _spot("Jama Masjid & Old Delhi walk", "Culture", 0, 2.0, "Morning"),
            _spot("Chandni Chowk food trail", "Food", 400, 2.0, "Afternoon"),
            _spot("Humayun's Tomb", "History", 40, 1.5, "Morning"),
            _spot("Qutub Minar", "History", 40, 1.5, "Afternoon"),
            _spot("India Gate & Rajpath", "Culture", 0, 1.5, "Evening"),
            _spot("Lotus Temple", "Culture", 0, 1.0, "Afternoon"),
            _spot("Akshardham Temple", "Culture", 0, 3.0, "Afternoon", FAMILY_FRIENDLY),
            _spot("Lodhi Garden picnic", "Nature", 0, 1.5, "Morning"),
            _spot("Hauz Khas Village", "Nightlife", 800, 2.5, "Evening", ADULTS),
            _spot("Dilli Haat crafts", "Shopping", 400, 2.0, "Afternoon"),
            _spot("Connaught Place shopping", "Shopping", 700, 2.0, "Afternoon"),
            _spot("Paranthe Wali Gali", "Food", 250, 1.0, "Morning"),
            _spot("National Museum", "Culture", 20, 2.5, "Afternoon"),
            _spot("Agrasen ki Baoli", "History", 0, 1.0, "Morning"),
            _spot("Sarojini Nagar Market", "Shopping", 500, 2.0, "Afternoon"),
            _spot("Khan Market dinner", "Food", 900, 1.5, "Evening", ADULTS),
            _spot("Purana Qila", "History", 25, 1.5, "Morning"),
            _spot("Garden of Five Senses", "Nature", 35, 1.5, "Evening"),
        ],
    },
    "Jaipur": {
        "state": "Rajasthan",
        "tagline": "The Pink City of forts, palaces and bazaars",
        "weather_note": "Dry heat by day; evenings are cooler, especially in winter.",
        "is_hill_station": False,
        "is_beach": False,
        "attractions": [
            _spot("Amber Fort (Amer)", "History", 100, 3.0, "Morning"),
            _spot("City Palace Jaipur", "History", 200, 2.0, "Morning"),
            _spot("Hawa Mahal photo stop", "Culture", 50, 1.0, "Morning"),
            _spot("Jantar Mantar", "History", 50, 1.5, "Afternoon"),
            _spot("Nahargarh Fort sunset", "Adventure", 50, 2.0, "Evening"),
            _spot("Jal Mahal view", "Nature", 0, 0.75, "Morning"),
            _spot("Albert Hall Museum", "Culture", 40, 1.5, "Afternoon"),
            _spot("Johari Bazaar jewellery & textiles", "Shopping", 700, 2.0, "Afternoon"),
            _spot("Bapu Bazaar souvenirs", "Shopping", 400, 1.5, "Afternoon"),
            _spot("Rajasthani thali dinner", "Food", 500, 1.5, "Evening"),
            _spot("Chokhi Dhani cultural village", "Culture", 800, 3.0, "Evening", FAMILY_FRIENDLY),
            _spot("Birla Mandir", "Culture", 0, 1.0, "Evening"),
            _spot("Jaigarh Fort", "History", 50, 2.0, "Morning"),
            _spot("Elephant / jeep ride near Amer", "Adventure", 900, 1.5, "Morning", FAMILY_FRIENDLY),
            _spot("LMB or Lassiwala snack stop", "Food", 180, 0.75, "Afternoon"),
            _spot("Night market stroll", "Nightlife", 300, 1.5, "Evening"),
            _spot("Galtaji Monkey Temple", "Culture", 0, 2.0, "Morning"),
            _spot("Central Park Jaipur evening", "Relaxation", 0, 1.0, "Evening"),
        ],
    },
    "Hyderabad": {
        "state": "Telangana",
        "tagline": "Nizami heritage, lakes and legendary biryani",
        "weather_note": "Hot Deccan climate; hydrate well in summer.",
        "is_hill_station": False,
        "is_beach": False,
        "attractions": [
            _spot("Charminar", "History", 20, 1.5, "Morning"),
            _spot("Laad Bazaar bangles", "Shopping", 400, 1.5, "Afternoon"),
            _spot("Chowmahalla Palace", "History", 80, 2.0, "Morning"),
            _spot("Golconda Fort", "History", 25, 3.0, "Morning"),
            _spot("Qutb Shahi Tombs", "History", 20, 1.5, "Afternoon"),
            _spot("Salar Jung Museum", "Culture", 50, 2.5, "Afternoon"),
            _spot("Hussain Sagar & Necklace Road", "Relaxation", 0, 1.5, "Evening"),
            _spot("Birla Mandir Hyderabad", "Culture", 0, 1.0, "Evening"),
            _spot("Ramoji Film City", "Adventure", 1600, 6.0, "Morning", FAMILY_FRIENDLY),
            _spot("Hitech City / Cyberabad photos", "Culture", 0, 1.5, "Afternoon"),
            _spot("Hyderabadi biryani lunch", "Food", 400, 1.0, "Afternoon"),
            _spot("Irani chai & Osmania biscuits", "Food", 120, 0.75, "Morning"),
            _spot("Shilparamam crafts village", "Shopping", 100, 2.0, "Evening"),
            _spot("Durgam Cheruvu lake", "Nature", 0, 1.5, "Evening"),
            _spot("Sound & light show at Golconda", "Culture", 80, 1.5, "Evening"),
            _spot("Jubilee Hills cafe evening", "Nightlife", 800, 2.0, "Evening", ADULTS),
            _spot("Nehru Zoological Park", "Nature", 50, 2.5, "Morning", FAMILY_FRIENDLY),
            _spot("Paigah Tombs", "History", 10, 1.5, "Afternoon"),
        ],
    },
    "Chennai": {
        "state": "Tamil Nadu",
        "tagline": "Marina sands, temples and filter coffee",
        "weather_note": "Hot and humid; sea breeze helps along the coast.",
        "is_hill_station": False,
        "is_beach": True,
        "attractions": [
            _spot("Marina Beach sunrise", "Relaxation", 0, 1.5, "Morning"),
            _spot("Kapaleeshwarar Temple", "Culture", 0, 1.5, "Morning"),
            _spot("Fort St. George", "History", 20, 1.5, "Morning"),
            _spot("Government Museum Egmore", "Culture", 25, 2.0, "Afternoon"),
            _spot("Santhome Cathedral", "Culture", 0, 1.0, "Afternoon"),
            _spot("Mahabalipuram day trip", "History", 800, 5.0, "Morning"),
            _spot("T. Nagar shopping", "Shopping", 600, 2.0, "Afternoon"),
            _spot("Pondy Bazaar", "Shopping", 400, 1.5, "Afternoon"),
            _spot("Filter coffee & tiffin breakfast", "Food", 150, 1.0, "Morning"),
            _spot("Chettinad or banana-leaf lunch", "Food", 350, 1.0, "Afternoon"),
            _spot("Elliot's Beach (Besant Nagar)", "Relaxation", 0, 1.5, "Evening"),
            _spot("Muttukadu boat house", "Adventure", 300, 2.0, "Morning", FAMILY_FRIENDLY),
            _spot("DakshinaChitra cultural village", "Culture", 150, 3.0, "Afternoon", FAMILY_FRIENDLY),
            _spot("Express Avenue / Phoenix mall", "Shopping", 700, 2.0, "Evening"),
            _spot("Besant Nagar evening cafes", "Nightlife", 600, 2.0, "Evening", ADULTS),
            _spot("Guindy National Park", "Nature", 30, 2.0, "Morning", FAMILY_FRIENDLY),
            _spot("Valluvar Kottam", "Culture", 0, 1.0, "Afternoon"),
            _spot("Puliyodarai and sundal snack stop", "Food", 120, 0.75, "Evening"),
        ],
    },
    "Kochi": {
        "state": "Kerala",
        "tagline": "Harbour city of Chinese nets, spice and backwaters",
        "weather_note": "Tropical and humid; light rain is common.",
        "is_hill_station": False,
        "is_beach": True,
        "attractions": [
            _spot("Fort Kochi Chinese fishing nets", "Culture", 0, 1.5, "Morning"),
            _spot("St. Francis Church", "History", 0, 0.75, "Morning"),
            _spot("Dutch Palace (Mattancherry)", "History", 20, 1.5, "Morning"),
            _spot("Jew Town & Paradesi Synagogue", "Culture", 10, 1.5, "Afternoon"),
            _spot("Spice market walk", "Shopping", 400, 1.5, "Afternoon"),
            _spot("Marine Drive Kochi", "Relaxation", 0, 1.5, "Evening"),
            _spot("Kathakali performance", "Culture", 400, 2.0, "Evening"),
            _spot("Backwater boat ride", "Nature", 1200, 3.0, "Morning"),
            _spot("Cherai Beach", "Relaxation", 0, 2.0, "Afternoon"),
            _spot("Kerala sadya lunch", "Food", 350, 1.0, "Afternoon"),
            _spot("Seafood at Fort Kochi", "Food", 700, 1.5, "Evening"),
            _spot("Hill Palace Museum", "History", 30, 2.0, "Afternoon"),
            _spot("Princess Street cafes", "Food", 400, 1.5, "Evening", ADULTS),
            _spot("Sunset at Fort Kochi beach", "Relaxation", 0, 1.0, "Evening"),
            _spot("Local art cafe hopping", "Nightlife", 500, 2.0, "Evening", ADULTS),
            _spot("Mangroves / kayaking (nearby)", "Adventure", 900, 2.5, "Morning", ADULTS),
            _spot("Indo-Portuguese Museum", "History", 20, 1.0, "Afternoon"),
            _spot("Santa Cruz Basilica", "Culture", 0, 0.75, "Morning"),
        ],
    },
    "Ooty": {
        "state": "Tamil Nadu",
        "tagline": "Nilgiri hill station of tea, lakes and toy trains",
        "weather_note": "Cool to cold; pack layers and a light rain jacket.",
        "is_hill_station": True,
        "is_beach": False,
        "attractions": [
            _spot("Ooty Botanical Gardens", "Nature", 30, 2.0, "Morning"),
            _spot("Ooty Lake boat ride", "Relaxation", 150, 1.5, "Afternoon", FAMILY_FRIENDLY),
            _spot("Doddabetta Peak", "Adventure", 20, 1.5, "Morning"),
            _spot("Nilgiri Mountain Railway toy train", "Culture", 300, 2.5, "Morning", FAMILY_FRIENDLY),
            _spot("Tea factory & museum", "Culture", 50, 1.5, "Afternoon"),
            _spot("Rose Garden", "Nature", 30, 1.5, "Morning"),
            _spot("Pykara Lake & falls", "Nature", 200, 3.0, "Morning"),
            _spot("Avalanche Lake trip", "Adventure", 600, 4.0, "Morning", ADULTS),
            _spot("Thread Garden", "Culture", 60, 1.0, "Afternoon", FAMILY_FRIENDLY),
            _spot("Charing Cross shopping", "Shopping", 400, 1.5, "Afternoon"),
            _spot("Chocolate and tea shopping", "Shopping", 500, 1.5, "Afternoon"),
            _spot("Homestyle Nilgiri dinner", "Food", 400, 1.0, "Evening"),
            _spot("Evening lakeside walk", "Relaxation", 0, 1.0, "Evening"),
            _spot("Coonoor day outing", "Nature", 500, 4.0, "Morning"),
            _spot("Campfire evening (seasonal)", "Nightlife", 300, 2.0, "Evening", FAMILY_FRIENDLY),
            _spot("St. Stephen's Church", "Culture", 0, 0.75, "Morning"),
            _spot("Elk Hill viewpoint", "Adventure", 0, 1.5, "Evening"),
            _spot("Varkey’s / local bakery stop", "Food", 200, 0.75, "Afternoon"),
        ],
    },
    "Manali": {
        "state": "Himachal Pradesh",
        "tagline": "Himalayan valleys, adventure and apple orchards",
        "weather_note": "Cold mornings and nights; snow possible in winter.",
        "is_hill_station": True,
        "is_beach": False,
        "attractions": [
            _spot("Hadimba Devi Temple", "Culture", 0, 1.5, "Morning"),
            _spot("Old Manali cafes", "Food", 500, 2.0, "Afternoon", ADULTS),
            _spot("Mall Road stroll & shopping", "Shopping", 400, 2.0, "Evening"),
            _spot("Solang Valley adventure", "Adventure", 1500, 4.0, "Morning"),
            _spot("Rohtang / Atal Tunnel viewpoint", "Adventure", 1200, 5.0, "Morning", ADULTS),
            _spot("Vashisht hot springs", "Relaxation", 0, 1.5, "Afternoon"),
            _spot("Manu Temple", "Culture", 0, 1.0, "Morning"),
            _spot("Van Vihar National Park", "Nature", 20, 1.5, "Morning", FAMILY_FRIENDLY),
            _spot("Jogini Falls trek", "Adventure", 0, 3.0, "Morning", ADULTS),
            _spot("Beas river walk", "Nature", 0, 1.5, "Evening"),
            _spot("Tibetan Monastery", "Culture", 0, 1.0, "Afternoon"),
            _spot("Himachali dham / siddu tasting", "Food", 300, 1.0, "Afternoon"),
            _spot("Club House activities", "Relaxation", 200, 2.0, "Afternoon", FAMILY_FRIENDLY),
            _spot("Night market on Mall Road", "Nightlife", 350, 1.5, "Evening"),
            _spot("Paragliding (seasonal)", "Adventure", 2500, 2.0, "Morning", ADULTS),
            _spot("Apple orchard visit (seasonal)", "Nature", 0, 1.5, "Morning"),
            _spot("Hidimba forest walk", "Nature", 0, 1.5, "Evening"),
            _spot("Local trout lunch", "Food", 450, 1.0, "Afternoon"),
        ],
    },
    "Munnar": {
        "state": "Kerala",
        "tagline": "Rolling tea estates in the Western Ghats",
        "weather_note": "Cool and misty; carry a warm layer even in summer.",
        "is_hill_station": True,
        "is_beach": False,
        "attractions": [
            _spot("Tea plantation walk", "Nature", 0, 2.0, "Morning"),
            _spot("Eravikulam National Park (Rajamalai)", "Nature", 200, 3.0, "Morning"),
            _spot("Mattupetty Dam", "Nature", 30, 1.5, "Afternoon", FAMILY_FRIENDLY),
            _spot("Echo Point", "Nature", 0, 1.0, "Afternoon"),
            _spot("Top Station viewpoint", "Adventure", 400, 3.0, "Morning"),
            _spot("Anamudi viewpoint area", "Adventure", 0, 2.0, "Morning"),
            _spot("Tea Museum", "Culture", 125, 1.5, "Afternoon"),
            _spot("Blossom Park", "Relaxation", 30, 1.5, "Afternoon", FAMILY_FRIENDLY),
            _spot("Attukal Waterfalls", "Nature", 0, 1.5, "Morning"),
            _spot("Spice garden visit", "Culture", 150, 1.5, "Afternoon"),
            _spot("Munnar town shopping", "Shopping", 400, 1.5, "Evening"),
            _spot("Kerala plantation lunch", "Food", 350, 1.0, "Afternoon"),
            _spot("Sunset at a viewpoint", "Relaxation", 0, 1.0, "Evening"),
            _spot("Kundala Lake boating", "Relaxation", 150, 1.5, "Afternoon", FAMILY_FRIENDLY),
            _spot("Mild trekking trail", "Adventure", 0, 2.5, "Morning", ADULTS),
            _spot("Campfire & local snacks", "Nightlife", 250, 2.0, "Evening", FAMILY_FRIENDLY),
            _spot("Lockhart Gap viewpoint", "Adventure", 0, 1.5, "Evening"),
            _spot("Pothamedu viewpoint", "Nature", 0, 1.5, "Morning"),
        ],
    },
}


SUPPORTED_DESTINATIONS = list(DESTINATIONS.keys())


def resolve_destination(raw_name):
    """
    Map free-text input to a catalogue key.

    Returns the official destination name, or None if unknown.
    """
    if not raw_name:
        return None
    cleaned = " ".join(str(raw_name).strip().lower().split())
    if cleaned in DESTINATION_ALIASES:
        return DESTINATION_ALIASES[cleaned]
    for official in DESTINATIONS:
        if official.lower() == cleaned:
            return official
    return None
